image: node:9

before_script:
  - yarn install

cache:
  paths:
  - node_modules/

stages:
  - test
  - publish

test:
  stage: test
  script:
    - yarn build
    - yarn test

publish:
  stage: publish
  only:
    - tags
    - triggers
  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - yarn publish
